Split up View type to improve TS linting
slackapi/node-slack-sdk pull request #1276
Opened 2021-06-29 06:36 UTC by alexjamesmalcolm

###  Summary

There a `View` type. It has three subset types `modal`, `home`, and `workflow_step`. As I've discovered while consuming `@slack/bolt` there is a benefit to split these three up. Specifically that the `modal` subset requires the `title` field but the other two subsets have no use for it. If a consumer of this attempts to send a `modal` view without a `title` they will receive an error so by splitting up the single `interface` into three we can prevent the consumer from having to make the same mistake as myself to learn that although the `title` field is optional for a `view`, when `type: "modal"` is the case the `title` field is required.

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2021-06-29 06:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slackapi/node-slack-sdk?pullRequest=1276) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slackapi/node-slack-sdk?pullRequest=1276) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slackapi/node-slack-sdk?pullRequest=1276) it.</sub>

2021-06-29 23:54 UTC, seratch requested changes
Thanks for the great pull request! Can you check my comment?

2021-06-29 23:54 UTC, seratch commented on packages/types/src/index.ts
> +  submit_disabled?: boolean; // defaults to false
The API document may not be clear enough but as of today, this option is available only for "workflow_step" type modals. Can you remove `submit_disabled` from this type definition? 
```suggestion
```

2021-06-30 01:37 UTC, seratch approved these changes
LGTM! Before merging this, I would like to wait for others' comments for a few days

2021-07-01 02:43 UTC, misscoded approved these changes

2021-08-18 16:47 UTC, srajiang approved these changes

2021-08-18 16:48 UTC, srajiang commented
I think we should be good to merge these changes in, unless there was further discussion to be had on this @seratch!

2021-08-18 22:05 UTC, seratch commented
Thanks @srajiang, yes, we can merge this PR 👍

2021-08-18 22:05 UTC, merged