Move token sending to authorization header instead of body parameter
slackapi/node-slack-sdk pull request #1337
Opened 2021-09-15 18:24 UTC by filmaj

Fixes #1132

I also removed some trailing whitespace because that's the kind of nitpicky dude I am

2021-09-15 18:28 UTC, filmaj commented on packages/web-api/src/WebClient.spec.js
> -            assert.deepInclude(parts.fields, { fieldname: 'token', value: token });
With the token no longer a part of the request body, this part needed removal.

2021-09-16 00:08 UTC, seratch requested changes
I like the change! Can you check the two points I mentioned in comments?

2021-09-16 00:08 UTC, seratch commented on packages/web-api/src/WebClient.ts
> +    if (!headers.Authorization) headers.Authorization = `Bearer ${this.token}`;
`this.token` can be absent. For instance, some API calls (such as oauth.v2.access with code parameter, openid.connect.token with code parameter, api.test) do not require token in the authorization header. Can you update the logic to check if `this.token` exists too?

2021-09-16 00:08 UTC, seratch commented on packages/web-api/src/WebClient.spec.js
>        return this.client.apiCall('method', { foo: 'stringval', bar: 42, baz: false, team_id: 'T12345678' })
Can we override the token in the authorization header if a developer passes a token like `this.client.apiCall('method', { token: 'xoxb-' })`? Switching tokens is not a rare use case. For instance, the singleton `WebClient` does not hold any token and your app utilizes multiple user tokens for user related API calls.

2021-09-16 12:53 UTC, filmaj commented
@seratch I believe I have addressed your comments, and also added another test for the Authorization header overriding behaviour via `apiCall()` options parameter.

2021-09-16 12:57 UTC, seratch approved these changes
@filmaj LGTM! Having unit tests this way makes reviews easier 👍

2021-09-16 18:50 UTC, stevengill approved these changes
Looks great!

2021-09-17 00:37 UTC, merged