Adding basic documentation to go along with the openid-connect example
slackapi/node-slack-sdk pull request #1372
Opened 2021-11-04 20:05 UTC by filmaj

Fixes #1356

Very basic first pass at this... is this sufficient? What is it missing?

2021-11-04 20:25 UTC, srajiang requested changes
Hows this for a slightly modified wording?

2021-11-04 20:25 UTC, srajiang commented on docs/_packages/web_api.md
> +By leveraging two APIs provided by `@slack/web-api`, [`openid.connect.token`](https://api.slack.com/methods/openid.connect.token)
```suggestion
**Sign in With Slack** via OpenID Connect gives users the ability to sign into your service using their Slack profile.

The `@slack/web-api` package supports the following API methods which you can use to implement **Sign in With Slack**: 

- [`openid.connect.token`](https://api.slack.com/methods/openid.connect.token)

```

2021-11-04 20:25 UTC, srajiang commented on docs/_packages/web_api.md
> +and [`openid.connect.userInfo`](https://api.slack.com/methods/openid.connect.userInfo), you can provide users the
```suggestion

- [`openid.connect.userInfo`](https://api.slack.com/methods/openid.connect.userInfo).

```

2021-11-04 20:25 UTC, srajiang commented on docs/_packages/web_api.md
> +A fully functioning [application example is available](https://github.com/slackapi/node-slack-sdk/blob/main/examples/openid-connect) for your perusal!
```suggestion
Here's a fully-functioning [sample application implementation](https://github.com/slackapi/node-slack-sdk/blob/main/examples/openid-connect) for your perusal!
```

2021-11-04 20:25 UTC, srajiang commented on docs/_packages/web_api.md
> +Full details on how the Sign in with Slack flow works, application setup, as well as helpful resources like a Sign in With Slack
```suggestion
💡 To read more about how **Sign in with Slack** works, and to access helpful resources like a Sign in With Slack
```

2021-11-04 20:25 UTC, srajiang commented on docs/_packages/web_api.md
> +button generator and other design assets are available on the [Authentication: Sign in with Slack](https://api.slack.com/authentication/sign-in-with-slack)
```suggestion
button generator and other design assets, check out: [Authentication: Sign in with Slack](https://api.slack.com/authentication/sign-in-with-slack)
```

2021-11-04 21:56 UTC, seratch commented
How about having a link from the oauth document page as well? https://github.com/slackapi/node-slack-sdk/issues/1356#issuecomment-961461320

2021-11-05 15:58 UTC, filmaj commented
@srajiang thank you for your suggestions, I have incorporated them!

@seratch I added a 'limitations' section to the oauth package docs calling out the inability to use the package to implement Sign in with Slack, and linked to the new web-api package doc on the topic.

What do you all think of the latest version of these docs?

2021-11-05 16:39 UTC, srajiang approved these changes

2021-11-06 00:02 UTC, seratch approved these changes
LGTM

2021-11-06 00:02 UTC, merged