Add rich text types
slackapi/node-slack-sdk pull request #1643
Opened 2023-08-15 14:58 UTC by chrisronline

###  Summary

JIRA: https://jira.tinyspeck.com/browse/BK-2409

This PR adds types for `rich_text` and `rich_text_input`. We can merge and release this after the tentative GA date for [#feat-bk-richtext](https://slack.enterprise.slack.com/archives/C04S6CW6B2T) of 8/23. 

This particular block is intentionally incomplete, as it's not clear how much we should document the inner workings of `rich_text`. I will add some CSC folks here to verify this thinking for us.

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2023-08-24 18:23 UTC, filmaj requested changes
Hey @chrisronline left a few comments, and also rebased your branch with the latest `main` now that I fixed the build 😅 . Also our CI failed, I guess it doesn't like using `object` type and wants to use `Record<string, any>` or some such.

2023-09-29 18:53 UTC, filmaj approved these changes
I redid a lot of stuff in here so this approval shouldn't count for much.

2023-09-29 19:02 UTC, filmaj commented
BTW I integrated this with the web-api and bolt-js projects and all the tests passed OK 👍

2023-09-29 19:04 UTC, misscoded approved these changes
LGTM! :shipit: Love the degree of commenting; makes everything super clear!

2023-09-29 19:08 UTC, merged